export enum SceneType {
  FIRST_VIEW = 'FIRST_VIEW',
  ORTHER = 'ORTHER',
  CLASS_ROOM_HALLWAY = 'CLASS_ROOM_HALLWAY',
}

export enum ViewType {
  IMAGE_3D = 'IMAGE_3D',
  IMAGE_360 = 'IMAGE_360',
}

export enum RoomType {
  EXAMINATION = 'EXAMINATION',
  STUDY = 'STUDY',
  TESTING = 'TESTING',
  VIP_TESTING = 'VIP_TESTING',
  MATHEMETIC_EXPERIENCE = 'MATHEMETIC_EXPERIENCE',
  MATHEMETIC_HISTORY = 'MATHEMETIC_HISTORY',
}

export enum AreaType {
  MAIN = 'MAIN',
  HISTORY = 'HISTORY',
  STUDY = 'STUDY',
  EXPERIENCE = 'EXPERIENCE',
}
